#!/bin/bash
# Generate French and Italian pages from English templates
# Usage: bash generate-lang.sh [fr|it]
#
# NOTE: Product pages are now generated by generate-products.py (Python3).
# This script only handles the main content pages.

LANG=$1
SRC_DIR="/home/v/bbq/grillcraftbbq.com/en"
DST_DIR="/home/v/bbq/grillcraftbbq.com/$LANG"

if [ "$LANG" != "fr" ] && [ "$LANG" != "it" ]; then
  echo "Usage: bash generate-lang.sh [fr|it]"
  echo "  fr - French"
  echo "  it - Italian"
  echo ""
  echo "To regenerate product pages for all languages, run:"
  echo "  python3 generate-products.py"
  exit 1
fi

echo "Generating $LANG pages..."
echo "WARNING: This will overwrite existing files in $DST_DIR"
echo "Press Ctrl+C to cancel, or Enter to continue..."
read -r

mkdir -p "$DST_DIR"

# Nav labels per language
if [ "$LANG" = "fr" ]; then
  NAV_HOME="Domicile"
  NAV_PRODUCTS="Des Produits"
  NAV_GASTRO="La Gastronomie"
  NAV_PRIVATE="Menage Prive"
  NAV_CABINET="Armoire Fumeur"
  NAV_OFFSET="Offset BBQ &amp; Grill"
  NAV_BRAT="Brat und Backofen"
  NAV_CATERING="Catering"
  NAV_ABOUT="A Propos"
  NAV_CONTACT="Contacter"
  NAV_PRIVACY="Confidentialite"
  NAV_SHIPPING="Livraison &amp; Retours"
  NAV_STORE="Politique du Magasin"
  NAV_IMPRINT="Mentions Legales"
  NAV_TITLE_SUFFIX="GrillCraft BBQ"
  FOOTER_NAV="Navigation"
  FOOTER_PROD="Produits"
  FOOTER_LEGAL="Legal"
  FOOTER_CONTACT="Contacter"
  COUNTRY="Suisse"
  CITY="Winterthour"
elif [ "$LANG" = "it" ]; then
  NAV_HOME="Casa"
  NAV_PRODUCTS="Prodotti"
  NAV_GASTRO="Gastronomia"
  NAV_PRIVATE="Domestico Privato"
  NAV_CABINET="Fumatore da Armadio"
  NAV_OFFSET="Offset BBQ &amp; Grill"
  NAV_BRAT="Brat und Backofen"
  NAV_CATERING="Ristorazione"
  NAV_ABOUT="Chi Siamo"
  NAV_CONTACT="Contatto"
  NAV_PRIVACY="Privacy"
  NAV_SHIPPING="Spedizione &amp; Resi"
  NAV_STORE="Politica del Negozio"
  NAV_IMPRINT="Impronta"
  NAV_TITLE_SUFFIX="GrillCraft BBQ"
  FOOTER_NAV="Navigazione"
  FOOTER_PROD="Prodotti"
  FOOTER_LEGAL="Legale"
  FOOTER_CONTACT="Contatto"
  COUNTRY="Svizzera"
  CITY="Winterthur"
fi

for page in index produkte gastronomie private-haushalt cabinet-smoker offset-bbq-grill brat-und-backoefen catering uber-uns contact datenschutzerklarung shipping-and-returns store-policy impressum; do
  src="$SRC_DIR/$page.html"
  dst="$DST_DIR/$page.html"
  if [ -f "$src" ]; then
    echo "  Creating $page.html..."
    
    # Step 1: Copy the English source
    cp "$src" "$dst.tmp"
    
    # Step 2: Set the language
    sed -i 's|<html lang="en">|<html lang="'"$LANG"'">|g' "$dst.tmp"
    
    # Step 3: Replace all /en/ URLs with /LANG/ URLs
    # But be careful not to double-replace
    sed -i 's|/en/|/'"$LANG"'/|g' "$dst.tmp"
    
    # Step 4: Fix the lang switcher - each language should appear exactly once
    # The EN page has: EN / FR / IT
    # FR page should have: FR(active) / EN / IT
    # IT page should have: IT(active) / EN / FR
    if [ "$LANG" = "fr" ]; then
      sed -i 's|class="active">EN</a><a href="/fr/">FR</a><a href="/it/">IT</a>|class="active">FR</a><a href="/en/">EN</a><a href="/it/">IT</a>|g' "$dst.tmp"
    elif [ "$LANG" = "it" ]; then
      sed -i 's|class="active">EN</a><a href="/fr/">FR</a><a href="/it/">IT</a>|class="active">IT</a><a href="/en/">EN</a><a href="/fr/">FR</a>|g' "$dst.tmp"
    fi
    
    mv "$dst.tmp" "$dst"
    echo "    Done - needs manual translation of body text"
  else
    echo "  Skipping $page.html (not found)"
  fi
done

echo ""
echo "Done! Main pages generated for $LANG."
echo ""
echo "To also generate product pages, run:"
echo "  python3 generate-products.py"
echo ""
echo "Note: Body text content is still in English and needs translation."
